[package]
name = "game_engine"
version = "0.1.0"
authors = ["zendpen <jacobzzxy@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-win = "0.11"
vulkano-shaders = "0.11"
winit = "0.18"
